version: "3.3"
services:
  frontend:
    image: node:lts-alpine3.13
    container_name: frontend
    volumes:
      - ./app/frontend:/frontend
    working_dir: /frontend
    entrypoint: >
      sh -c "npm install
      && npm run dev"

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    env_file: ./docker.env
    volumes:
      - ./app/backend:/backend
      - ./app/frontend/dist:/backend/client    
    working_dir: /backend
    ports:
      - 80:3001
    entrypoint: > 
      sh -c "npm install
      && npm run schema:drop
      && npm run schema:sync
      && npm run seed:run
      && npm run build
      && npm run start:dev"

  db:
    image: postgres:13.3-alpine
    container_name: db
    user: postgres
    env_file: ./docker.env
    volumes:
      - ./app/db:/db
    working_dir: /db
    ports:
      - 5432:5432
    entrypoint: sh -c "/db/init-user-db.sh; while true; do sleep 1; done;"
